[functions.jobs-runner]
verify_jwt = false

[[cron]]
function = "jobs-runner"
schedule = "*/30 * * * *"
payload = "{\"task\":\"akahu\"}"

[[cron]]
function = "jobs-runner"
schedule = "0 2 * * *"
payload = "{\"task\":\"envelopes\"}"
