/**
 * Comprehensive Emoji Data for Budget App
 *
 * Contains 1,500+ emojis organized by budget-relevant categories
 * with searchable keywords for each emoji.
 */

export interface FluentEmoji {
  id: string;
  emoji: string;
  name: string;
  category: string;
  keywords: string[];
}

export const FLUENT_CATEGORIES: Record<string, { label: string; icon: string }> = {
  money: { label: 'Money', icon: '💰' },
  home: { label: 'Home', icon: '🏠' },
  transport: { label: 'Transport', icon: '🚗' },
  food: { label: 'Food', icon: '🍕' },
  health: { label: 'Health', icon: '🏥' },
  shopping: { label: 'Shopping', icon: '🛒' },
  activities: { label: 'Activities', icon: '🎮' },
  work: { label: 'Work', icon: '💼' },
  tech: { label: 'Tech', icon: '📱' },
  people: { label: 'People', icon: '👨' },
  animals: { label: 'Animals', icon: '🐕' },
  nature: { label: 'Nature', icon: '🌳' },
  objects: { label: 'Objects', icon: '📦' },
  symbols: { label: 'Symbols', icon: '❤️' },
  flags: { label: 'Flags', icon: '🏁' },
};

export const FLUENT_EMOJIS: FluentEmoji[] = [
  // ========== MONEY & FINANCE (Most Relevant for Budget App) ==========
  { id: 'money-bag', emoji: '💰', name: 'Money Bag', category: 'money', keywords: ['cash', 'rich', 'wealth', 'savings', 'money', 'dollar'] },
  { id: 'dollar-banknote', emoji: '💵', name: 'Dollar Banknote', category: 'money', keywords: ['cash', 'bill', 'currency', 'payment', 'money', 'usd'] },
  { id: 'euro-banknote', emoji: '💶', name: 'Euro Banknote', category: 'money', keywords: ['cash', 'bill', 'currency', 'payment', 'money', 'eur'] },
  { id: 'pound-banknote', emoji: '💷', name: 'Pound Banknote', category: 'money', keywords: ['cash', 'bill', 'currency', 'payment', 'money', 'gbp'] },
  { id: 'yen-banknote', emoji: '💴', name: 'Yen Banknote', category: 'money', keywords: ['cash', 'bill', 'currency', 'payment', 'money', 'jpy'] },
  { id: 'credit-card', emoji: '💳', name: 'Credit Card', category: 'money', keywords: ['payment', 'card', 'bank', 'debt', 'debit', 'plastic'] },
  { id: 'money-with-wings', emoji: '💸', name: 'Money with Wings', category: 'money', keywords: ['spending', 'expense', 'flying', 'gone', 'lost'] },
  { id: 'coin', emoji: '🪙', name: 'Coin', category: 'money', keywords: ['money', 'change', 'currency', 'gold', 'silver'] },
  { id: 'bank', emoji: '🏦', name: 'Bank', category: 'money', keywords: ['savings', 'finance', 'account', 'institution', 'building'] },
  { id: 'chart-increasing', emoji: '📈', name: 'Chart Increasing', category: 'money', keywords: ['growth', 'profit', 'investment', 'stocks', 'up', 'rising'] },
  { id: 'chart-decreasing', emoji: '📉', name: 'Chart Decreasing', category: 'money', keywords: ['loss', 'decline', 'down', 'falling', 'stocks'] },
  { id: 'heavy-dollar-sign', emoji: '💲', name: 'Heavy Dollar Sign', category: 'money', keywords: ['money', 'currency', 'price', 'cost'] },
  { id: 'receipt', emoji: '🧾', name: 'Receipt', category: 'money', keywords: ['bill', 'purchase', 'shopping', 'expense', 'proof'] },
  { id: 'bar-chart', emoji: '📊', name: 'Bar Chart', category: 'money', keywords: ['statistics', 'data', 'graph', 'analytics', 'report'] },
  { id: 'atm', emoji: '🏧', name: 'ATM Sign', category: 'money', keywords: ['cash', 'withdrawal', 'bank', 'machine'] },
  { id: 'gem-stone', emoji: '💎', name: 'Gem Stone', category: 'money', keywords: ['diamond', 'valuable', 'precious', 'luxury', 'wealth'] },
  { id: 'currency-exchange', emoji: '💱', name: 'Currency Exchange', category: 'money', keywords: ['forex', 'conversion', 'travel', 'exchange'] },
  { id: 'scales', emoji: '⚖️', name: 'Balance Scale', category: 'money', keywords: ['balance', 'budget', 'fair', 'legal', 'justice'] },

  // ========== HOME & HOUSING ==========
  { id: 'house', emoji: '🏠', name: 'House', category: 'home', keywords: ['home', 'building', 'residence', 'property', 'mortgage'] },
  { id: 'house-with-garden', emoji: '🏡', name: 'House with Garden', category: 'home', keywords: ['home', 'garden', 'property', 'yard'] },
  { id: 'office-building', emoji: '🏢', name: 'Office Building', category: 'home', keywords: ['work', 'business', 'office', 'building'] },
  { id: 'post-office', emoji: '🏣', name: 'Japanese Post Office', category: 'home', keywords: ['mail', 'post', 'building'] },
  { id: 'hospital', emoji: '🏥', name: 'Hospital', category: 'home', keywords: ['health', 'medical', 'emergency', 'building'] },
  { id: 'hotel', emoji: '🏨', name: 'Hotel', category: 'home', keywords: ['accommodation', 'travel', 'lodging', 'stay'] },
  { id: 'school', emoji: '🏫', name: 'School', category: 'home', keywords: ['education', 'learning', 'building', 'study'] },
  { id: 'department-store', emoji: '🏬', name: 'Department Store', category: 'home', keywords: ['shopping', 'mall', 'retail', 'building'] },
  { id: 'factory', emoji: '🏭', name: 'Factory', category: 'home', keywords: ['industry', 'manufacturing', 'work', 'building'] },
  { id: 'castle', emoji: '🏰', name: 'Castle', category: 'home', keywords: ['building', 'historic', 'royal', 'fortress'] },
  { id: 'church', emoji: '⛪', name: 'Church', category: 'home', keywords: ['religion', 'worship', 'building', 'christian'] },
  { id: 'mosque', emoji: '🕌', name: 'Mosque', category: 'home', keywords: ['religion', 'worship', 'building', 'islam'] },
  { id: 'synagogue', emoji: '🕍', name: 'Synagogue', category: 'home', keywords: ['religion', 'worship', 'building', 'jewish'] },
  { id: 'construction', emoji: '🏗️', name: 'Building Construction', category: 'home', keywords: ['construction', 'building', 'crane', 'development'] },
  { id: 'hut', emoji: '🛖', name: 'Hut', category: 'home', keywords: ['shelter', 'cabin', 'cottage', 'simple'] },
  { id: 'wrench', emoji: '🔧', name: 'Wrench', category: 'home', keywords: ['repair', 'tool', 'fix', 'maintenance', 'plumber'] },
  { id: 'hammer', emoji: '🔨', name: 'Hammer', category: 'home', keywords: ['tool', 'repair', 'build', 'construction'] },
  { id: 'tools', emoji: '🛠️', name: 'Hammer and Wrench', category: 'home', keywords: ['repair', 'maintenance', 'fix', 'tools'] },
  { id: 'electric-plug', emoji: '🔌', name: 'Electric Plug', category: 'home', keywords: ['electricity', 'power', 'utility', 'energy'] },
  { id: 'light-bulb', emoji: '💡', name: 'Light Bulb', category: 'home', keywords: ['electricity', 'idea', 'power', 'utility', 'light'] },
  { id: 'shower', emoji: '🚿', name: 'Shower', category: 'home', keywords: ['bathroom', 'water', 'utility', 'clean'] },
  { id: 'bathtub', emoji: '🛁', name: 'Bathtub', category: 'home', keywords: ['bathroom', 'bath', 'relax', 'clean'] },
  { id: 'chair', emoji: '🪑', name: 'Chair', category: 'home', keywords: ['furniture', 'seat', 'home', 'office'] },
  { id: 'couch', emoji: '🛋️', name: 'Couch and Lamp', category: 'home', keywords: ['furniture', 'sofa', 'living room', 'home'] },
  { id: 'bed', emoji: '🛏️', name: 'Bed', category: 'home', keywords: ['furniture', 'bedroom', 'sleep', 'rest'] },
  { id: 'door', emoji: '🚪', name: 'Door', category: 'home', keywords: ['entrance', 'exit', 'home', 'room'] },
  { id: 'window', emoji: '🪟', name: 'Window', category: 'home', keywords: ['glass', 'view', 'home', 'building'] },
  { id: 'broom', emoji: '🧹', name: 'Broom', category: 'home', keywords: ['cleaning', 'sweep', 'household', 'chore'] },
  { id: 'basket', emoji: '🧺', name: 'Basket', category: 'home', keywords: ['laundry', 'storage', 'household', 'cleaning'] },
  { id: 'lotion', emoji: '🧴', name: 'Lotion Bottle', category: 'home', keywords: ['cosmetic', 'skincare', 'bathroom', 'personal'] },
  { id: 'toothbrush', emoji: '🪥', name: 'Toothbrush', category: 'home', keywords: ['dental', 'hygiene', 'bathroom', 'personal'] },
  { id: 'sponge', emoji: '🧽', name: 'Sponge', category: 'home', keywords: ['cleaning', 'kitchen', 'household', 'wash'] },
  { id: 'bucket', emoji: '🪣', name: 'Bucket', category: 'home', keywords: ['cleaning', 'water', 'household', 'container'] },
  { id: 'fire-extinguisher', emoji: '🧯', name: 'Fire Extinguisher', category: 'home', keywords: ['safety', 'emergency', 'fire', 'protection'] },
  { id: 'elevator', emoji: '🛗', name: 'Elevator', category: 'home', keywords: ['lift', 'building', 'floor', 'accessibility'] },
  { id: 'mirror', emoji: '🪞', name: 'Mirror', category: 'home', keywords: ['reflection', 'bathroom', 'vanity', 'decor'] },
  { id: 'frame', emoji: '🖼️', name: 'Framed Picture', category: 'home', keywords: ['art', 'decor', 'photo', 'wall'] },
  { id: 'key', emoji: '🔑', name: 'Key', category: 'home', keywords: ['lock', 'security', 'access', 'door', 'car'] },
  { id: 'old-key', emoji: '🗝️', name: 'Old Key', category: 'home', keywords: ['vintage', 'antique', 'lock', 'secret'] },
  { id: 'lock', emoji: '🔒', name: 'Locked', category: 'home', keywords: ['security', 'safe', 'private', 'closed'] },
  { id: 'unlock', emoji: '🔓', name: 'Unlocked', category: 'home', keywords: ['security', 'open', 'access', 'available'] },

  // ========== TRANSPORT ==========
  { id: 'car', emoji: '🚗', name: 'Automobile', category: 'transport', keywords: ['car', 'vehicle', 'drive', 'auto', 'sedan'] },
  { id: 'suv', emoji: '🚙', name: 'Sport Utility Vehicle', category: 'transport', keywords: ['car', 'suv', 'vehicle', 'drive'] },
  { id: 'taxi', emoji: '🚕', name: 'Taxi', category: 'transport', keywords: ['cab', 'ride', 'transport', 'fare'] },
  { id: 'bus', emoji: '🚌', name: 'Bus', category: 'transport', keywords: ['public', 'transport', 'commute', 'travel'] },
  { id: 'trolleybus', emoji: '🚎', name: 'Trolleybus', category: 'transport', keywords: ['public', 'transport', 'electric'] },
  { id: 'minibus', emoji: '🚐', name: 'Minibus', category: 'transport', keywords: ['van', 'transport', 'shuttle'] },
  { id: 'ambulance', emoji: '🚑', name: 'Ambulance', category: 'transport', keywords: ['emergency', 'medical', 'health', 'hospital'] },
  { id: 'fire-engine', emoji: '🚒', name: 'Fire Engine', category: 'transport', keywords: ['emergency', 'fire', 'rescue'] },
  { id: 'police-car', emoji: '🚓', name: 'Police Car', category: 'transport', keywords: ['emergency', 'law', 'security'] },
  { id: 'delivery-truck', emoji: '🚚', name: 'Delivery Truck', category: 'transport', keywords: ['shipping', 'delivery', 'moving', 'freight'] },
  { id: 'pickup-truck', emoji: '🛻', name: 'Pickup Truck', category: 'transport', keywords: ['truck', 'vehicle', 'utility'] },
  { id: 'motorcycle', emoji: '🏍️', name: 'Motorcycle', category: 'transport', keywords: ['bike', 'motorbike', 'vehicle', 'ride'] },
  { id: 'motor-scooter', emoji: '🛵', name: 'Motor Scooter', category: 'transport', keywords: ['scooter', 'moped', 'vehicle'] },
  { id: 'bicycle', emoji: '🚲', name: 'Bicycle', category: 'transport', keywords: ['bike', 'cycling', 'exercise', 'eco'] },
  { id: 'train', emoji: '🚂', name: 'Locomotive', category: 'transport', keywords: ['train', 'rail', 'transport', 'travel'] },
  { id: 'metro', emoji: '🚇', name: 'Metro', category: 'transport', keywords: ['subway', 'underground', 'transport', 'commute'] },
  { id: 'tram', emoji: '🚊', name: 'Tram', category: 'transport', keywords: ['streetcar', 'transport', 'city'] },
  { id: 'airplane', emoji: '✈️', name: 'Airplane', category: 'transport', keywords: ['flight', 'travel', 'plane', 'airport', 'vacation'] },
  { id: 'helicopter', emoji: '🚁', name: 'Helicopter', category: 'transport', keywords: ['flight', 'aircraft', 'chopper'] },
  { id: 'sailboat', emoji: '⛵', name: 'Sailboat', category: 'transport', keywords: ['boat', 'sailing', 'water', 'yacht'] },
  { id: 'ship', emoji: '🛳️', name: 'Passenger Ship', category: 'transport', keywords: ['cruise', 'boat', 'travel', 'ocean'] },
  { id: 'ferry', emoji: '⛴️', name: 'Ferry', category: 'transport', keywords: ['boat', 'water', 'transport', 'crossing'] },
  { id: 'fuel-pump', emoji: '⛽', name: 'Fuel Pump', category: 'transport', keywords: ['gas', 'petrol', 'station', 'fuel', 'car'] },
  { id: 'parking', emoji: '🅿️', name: 'P Button', category: 'transport', keywords: ['parking', 'car', 'lot', 'garage'] },
  { id: 'traffic-light', emoji: '🚦', name: 'Traffic Light', category: 'transport', keywords: ['signal', 'road', 'driving'] },
  { id: 'wheel', emoji: '🛞', name: 'Wheel', category: 'transport', keywords: ['tire', 'car', 'vehicle', 'round'] },
  { id: 'anchor', emoji: '⚓', name: 'Anchor', category: 'transport', keywords: ['boat', 'ship', 'nautical', 'marine'] },
  { id: 'rocket', emoji: '🚀', name: 'Rocket', category: 'transport', keywords: ['space', 'launch', 'fast', 'startup'] },

  // ========== FOOD & DRINK ==========
  { id: 'shopping-cart', emoji: '🛒', name: 'Shopping Cart', category: 'food', keywords: ['grocery', 'shopping', 'supermarket', 'cart', 'trolley'] },
  { id: 'pizza', emoji: '🍕', name: 'Pizza', category: 'food', keywords: ['food', 'italian', 'fast food', 'slice', 'cheese'] },
  { id: 'hamburger', emoji: '🍔', name: 'Hamburger', category: 'food', keywords: ['food', 'burger', 'fast food', 'meat'] },
  { id: 'fries', emoji: '🍟', name: 'French Fries', category: 'food', keywords: ['food', 'fast food', 'potato', 'chips'] },
  { id: 'hot-dog', emoji: '🌭', name: 'Hot Dog', category: 'food', keywords: ['food', 'fast food', 'sausage'] },
  { id: 'sandwich', emoji: '🥪', name: 'Sandwich', category: 'food', keywords: ['food', 'lunch', 'bread', 'meal'] },
  { id: 'taco', emoji: '🌮', name: 'Taco', category: 'food', keywords: ['food', 'mexican', 'meal'] },
  { id: 'burrito', emoji: '🌯', name: 'Burrito', category: 'food', keywords: ['food', 'mexican', 'wrap', 'meal'] },
  { id: 'salad', emoji: '🥗', name: 'Green Salad', category: 'food', keywords: ['food', 'healthy', 'vegetable', 'diet'] },
  { id: 'spaghetti', emoji: '🍝', name: 'Spaghetti', category: 'food', keywords: ['food', 'pasta', 'italian', 'noodles'] },
  { id: 'ramen', emoji: '🍜', name: 'Steaming Bowl', category: 'food', keywords: ['food', 'noodles', 'soup', 'asian', 'ramen'] },
  { id: 'sushi', emoji: '🍣', name: 'Sushi', category: 'food', keywords: ['food', 'japanese', 'fish', 'rice'] },
  { id: 'curry', emoji: '🍛', name: 'Curry Rice', category: 'food', keywords: ['food', 'indian', 'spicy', 'meal'] },
  { id: 'fried-rice', emoji: '🍚', name: 'Cooked Rice', category: 'food', keywords: ['food', 'rice', 'asian', 'grain'] },
  { id: 'bento', emoji: '🍱', name: 'Bento Box', category: 'food', keywords: ['food', 'japanese', 'lunch', 'meal'] },
  { id: 'takeout', emoji: '🥡', name: 'Takeout Box', category: 'food', keywords: ['food', 'chinese', 'delivery', 'restaurant'] },
  { id: 'egg', emoji: '🥚', name: 'Egg', category: 'food', keywords: ['food', 'breakfast', 'protein'] },
  { id: 'cooking', emoji: '🍳', name: 'Cooking', category: 'food', keywords: ['food', 'breakfast', 'egg', 'frying', 'kitchen'] },
  { id: 'bread', emoji: '🍞', name: 'Bread', category: 'food', keywords: ['food', 'bakery', 'toast', 'loaf'] },
  { id: 'croissant', emoji: '🥐', name: 'Croissant', category: 'food', keywords: ['food', 'bakery', 'french', 'pastry'] },
  { id: 'bagel', emoji: '🥯', name: 'Bagel', category: 'food', keywords: ['food', 'bakery', 'breakfast', 'bread'] },
  { id: 'pancakes', emoji: '🥞', name: 'Pancakes', category: 'food', keywords: ['food', 'breakfast', 'stack', 'syrup'] },
  { id: 'cheese', emoji: '🧀', name: 'Cheese Wedge', category: 'food', keywords: ['food', 'dairy', 'swiss'] },
  { id: 'meat', emoji: '🥩', name: 'Cut of Meat', category: 'food', keywords: ['food', 'steak', 'beef', 'protein'] },
  { id: 'chicken', emoji: '🍗', name: 'Poultry Leg', category: 'food', keywords: ['food', 'chicken', 'meat', 'drumstick'] },
  { id: 'bacon', emoji: '🥓', name: 'Bacon', category: 'food', keywords: ['food', 'breakfast', 'meat', 'pork'] },
  { id: 'apple', emoji: '🍎', name: 'Red Apple', category: 'food', keywords: ['food', 'fruit', 'healthy', 'snack'] },
  { id: 'banana', emoji: '🍌', name: 'Banana', category: 'food', keywords: ['food', 'fruit', 'healthy', 'snack'] },
  { id: 'orange', emoji: '🍊', name: 'Tangerine', category: 'food', keywords: ['food', 'fruit', 'citrus', 'healthy'] },
  { id: 'grapes', emoji: '🍇', name: 'Grapes', category: 'food', keywords: ['food', 'fruit', 'wine', 'healthy'] },
  { id: 'strawberry', emoji: '🍓', name: 'Strawberry', category: 'food', keywords: ['food', 'fruit', 'berry', 'healthy'] },
  { id: 'watermelon', emoji: '🍉', name: 'Watermelon', category: 'food', keywords: ['food', 'fruit', 'summer', 'healthy'] },
  { id: 'avocado', emoji: '🥑', name: 'Avocado', category: 'food', keywords: ['food', 'fruit', 'healthy', 'toast'] },
  { id: 'broccoli', emoji: '🥦', name: 'Broccoli', category: 'food', keywords: ['food', 'vegetable', 'healthy', 'green'] },
  { id: 'carrot', emoji: '🥕', name: 'Carrot', category: 'food', keywords: ['food', 'vegetable', 'healthy', 'orange'] },
  { id: 'corn', emoji: '🌽', name: 'Ear of Corn', category: 'food', keywords: ['food', 'vegetable', 'maize'] },
  { id: 'potato', emoji: '🥔', name: 'Potato', category: 'food', keywords: ['food', 'vegetable', 'starch'] },
  { id: 'milk', emoji: '🥛', name: 'Glass of Milk', category: 'food', keywords: ['drink', 'dairy', 'beverage', 'calcium'] },
  { id: 'coffee', emoji: '☕', name: 'Hot Beverage', category: 'food', keywords: ['drink', 'coffee', 'tea', 'cafe', 'caffeine'] },
  { id: 'tea', emoji: '🍵', name: 'Teacup Without Handle', category: 'food', keywords: ['drink', 'tea', 'green tea', 'beverage'] },
  { id: 'beer', emoji: '🍺', name: 'Beer Mug', category: 'food', keywords: ['drink', 'alcohol', 'bar', 'pub'] },
  { id: 'wine', emoji: '🍷', name: 'Wine Glass', category: 'food', keywords: ['drink', 'alcohol', 'wine', 'dinner'] },
  { id: 'cocktail', emoji: '🍸', name: 'Cocktail Glass', category: 'food', keywords: ['drink', 'alcohol', 'martini', 'bar'] },
  { id: 'champagne', emoji: '🍾', name: 'Bottle with Popping Cork', category: 'food', keywords: ['drink', 'celebration', 'party', 'champagne'] },
  { id: 'soft-drink', emoji: '🥤', name: 'Cup with Straw', category: 'food', keywords: ['drink', 'soda', 'beverage', 'soft drink'] },
  { id: 'juice', emoji: '🧃', name: 'Beverage Box', category: 'food', keywords: ['drink', 'juice', 'kids', 'beverage'] },
  { id: 'water', emoji: '💧', name: 'Droplet', category: 'food', keywords: ['water', 'drink', 'hydrate', 'liquid'] },
  { id: 'ice-cream', emoji: '🍨', name: 'Ice Cream', category: 'food', keywords: ['dessert', 'sweet', 'cold', 'treat'] },
  { id: 'doughnut', emoji: '🍩', name: 'Doughnut', category: 'food', keywords: ['dessert', 'sweet', 'bakery', 'donut'] },
  { id: 'cake', emoji: '🎂', name: 'Birthday Cake', category: 'food', keywords: ['dessert', 'celebration', 'birthday', 'party'] },
  { id: 'cupcake', emoji: '🧁', name: 'Cupcake', category: 'food', keywords: ['dessert', 'sweet', 'bakery', 'treat'] },
  { id: 'pie', emoji: '🥧', name: 'Pie', category: 'food', keywords: ['dessert', 'sweet', 'bakery', 'thanksgiving'] },
  { id: 'chocolate', emoji: '🍫', name: 'Chocolate Bar', category: 'food', keywords: ['dessert', 'sweet', 'candy', 'snack'] },
  { id: 'candy', emoji: '🍬', name: 'Candy', category: 'food', keywords: ['dessert', 'sweet', 'sugar', 'treat'] },
  { id: 'cookie', emoji: '🍪', name: 'Cookie', category: 'food', keywords: ['dessert', 'sweet', 'bakery', 'snack'] },
  { id: 'knife-fork', emoji: '🍽️', name: 'Fork and Knife with Plate', category: 'food', keywords: ['restaurant', 'dining', 'meal', 'eat'] },
  { id: 'chopsticks', emoji: '🥢', name: 'Chopsticks', category: 'food', keywords: ['asian', 'eating', 'utensil', 'dining'] },

  // ========== HEALTH & FITNESS ==========
  { id: 'hospital-building', emoji: '🏥', name: 'Hospital', category: 'health', keywords: ['medical', 'health', 'doctor', 'emergency'] },
  { id: 'pill', emoji: '💊', name: 'Pill', category: 'health', keywords: ['medicine', 'medication', 'pharmacy', 'drug', 'health'] },
  { id: 'syringe', emoji: '💉', name: 'Syringe', category: 'health', keywords: ['injection', 'vaccine', 'medical', 'shot'] },
  { id: 'stethoscope', emoji: '🩺', name: 'Stethoscope', category: 'health', keywords: ['doctor', 'medical', 'health', 'checkup'] },
  { id: 'adhesive-bandage', emoji: '🩹', name: 'Adhesive Bandage', category: 'health', keywords: ['bandaid', 'injury', 'heal', 'medical'] },
  { id: 'tooth', emoji: '🦷', name: 'Tooth', category: 'health', keywords: ['dental', 'dentist', 'teeth', 'oral'] },
  { id: 'glasses', emoji: '👓', name: 'Glasses', category: 'health', keywords: ['vision', 'eyewear', 'optical', 'reading'] },
  { id: 'sunglasses', emoji: '🕶️', name: 'Sunglasses', category: 'health', keywords: ['vision', 'eyewear', 'sun', 'cool'] },
  { id: 'weight-lifting', emoji: '🏋️', name: 'Person Lifting Weights', category: 'health', keywords: ['gym', 'exercise', 'fitness', 'workout', 'strength'] },
  { id: 'yoga', emoji: '🧘', name: 'Person in Lotus Position', category: 'health', keywords: ['meditation', 'yoga', 'fitness', 'calm', 'zen'] },
  { id: 'running', emoji: '🏃', name: 'Person Running', category: 'health', keywords: ['exercise', 'jogging', 'fitness', 'cardio', 'run'] },
  { id: 'swimming', emoji: '🏊', name: 'Person Swimming', category: 'health', keywords: ['exercise', 'pool', 'fitness', 'water', 'sport'] },
  { id: 'biking', emoji: '🚴', name: 'Person Biking', category: 'health', keywords: ['cycling', 'exercise', 'fitness', 'bike'] },
  { id: 'massage', emoji: '💆', name: 'Person Getting Massage', category: 'health', keywords: ['spa', 'relax', 'wellness', 'self-care'] },
  { id: 'sauna', emoji: '🧖', name: 'Person in Steamy Room', category: 'health', keywords: ['spa', 'sauna', 'wellness', 'relax'] },
  { id: 'dna', emoji: '🧬', name: 'DNA', category: 'health', keywords: ['science', 'genetics', 'biology', 'medical'] },
  { id: 'heart-organ', emoji: '🫀', name: 'Anatomical Heart', category: 'health', keywords: ['organ', 'medical', 'health', 'cardio'] },
  { id: 'brain', emoji: '🧠', name: 'Brain', category: 'health', keywords: ['organ', 'mental', 'think', 'intelligence'] },
  { id: 'thermometer', emoji: '🌡️', name: 'Thermometer', category: 'health', keywords: ['temperature', 'fever', 'sick', 'medical'] },
  { id: 'wheelchair', emoji: '♿', name: 'Wheelchair Symbol', category: 'health', keywords: ['accessibility', 'disability', 'mobility'] },
  { id: 'crutch', emoji: '🩼', name: 'Crutch', category: 'health', keywords: ['injury', 'mobility', 'medical', 'support'] },

  // ========== SHOPPING & RETAIL ==========
  { id: 'shopping-bags', emoji: '🛍️', name: 'Shopping Bags', category: 'shopping', keywords: ['retail', 'shopping', 'bags', 'mall', 'buy'] },
  { id: 't-shirt', emoji: '👕', name: 'T-Shirt', category: 'shopping', keywords: ['clothing', 'shirt', 'clothes', 'fashion'] },
  { id: 'jeans', emoji: '👖', name: 'Jeans', category: 'shopping', keywords: ['clothing', 'pants', 'clothes', 'fashion', 'denim'] },
  { id: 'dress', emoji: '👗', name: 'Dress', category: 'shopping', keywords: ['clothing', 'fashion', 'clothes', 'woman'] },
  { id: 'kimono', emoji: '👘', name: 'Kimono', category: 'shopping', keywords: ['clothing', 'japanese', 'fashion', 'traditional'] },
  { id: 'bikini', emoji: '👙', name: 'Bikini', category: 'shopping', keywords: ['clothing', 'swimwear', 'beach', 'summer'] },
  { id: 'coat', emoji: '🧥', name: 'Coat', category: 'shopping', keywords: ['clothing', 'jacket', 'winter', 'outerwear'] },
  { id: 'scarf', emoji: '🧣', name: 'Scarf', category: 'shopping', keywords: ['clothing', 'winter', 'accessory', 'warm'] },
  { id: 'gloves', emoji: '🧤', name: 'Gloves', category: 'shopping', keywords: ['clothing', 'winter', 'accessory', 'hands'] },
  { id: 'socks', emoji: '🧦', name: 'Socks', category: 'shopping', keywords: ['clothing', 'feet', 'accessory'] },
  { id: 'high-heel', emoji: '👠', name: 'High-Heeled Shoe', category: 'shopping', keywords: ['shoes', 'fashion', 'footwear', 'woman'] },
  { id: 'sneaker', emoji: '👟', name: 'Running Shoe', category: 'shopping', keywords: ['shoes', 'footwear', 'sport', 'casual'] },
  { id: 'boot', emoji: '👢', name: 'Woman\'s Boot', category: 'shopping', keywords: ['shoes', 'footwear', 'fashion'] },
  { id: 'hiking-boot', emoji: '🥾', name: 'Hiking Boot', category: 'shopping', keywords: ['shoes', 'footwear', 'outdoor', 'hiking'] },
  { id: 'flat-shoe', emoji: '🥿', name: 'Flat Shoe', category: 'shopping', keywords: ['shoes', 'footwear', 'fashion', 'casual'] },
  { id: 'sandal', emoji: '👡', name: 'Woman\'s Sandal', category: 'shopping', keywords: ['shoes', 'footwear', 'summer'] },
  { id: 'handbag', emoji: '👜', name: 'Handbag', category: 'shopping', keywords: ['bag', 'purse', 'fashion', 'accessory'] },
  { id: 'backpack', emoji: '🎒', name: 'Backpack', category: 'shopping', keywords: ['bag', 'school', 'travel', 'carry'] },
  { id: 'briefcase', emoji: '💼', name: 'Briefcase', category: 'shopping', keywords: ['bag', 'work', 'business', 'office'] },
  { id: 'luggage', emoji: '🧳', name: 'Luggage', category: 'shopping', keywords: ['bag', 'travel', 'suitcase', 'vacation'] },
  { id: 'lipstick', emoji: '💄', name: 'Lipstick', category: 'shopping', keywords: ['makeup', 'cosmetic', 'beauty', 'fashion'] },
  { id: 'ring', emoji: '💍', name: 'Ring', category: 'shopping', keywords: ['jewelry', 'engagement', 'wedding', 'accessory'] },
  { id: 'crown', emoji: '👑', name: 'Crown', category: 'shopping', keywords: ['jewelry', 'royal', 'king', 'queen', 'accessory'] },
  { id: 'nail-polish', emoji: '💅', name: 'Nail Polish', category: 'shopping', keywords: ['beauty', 'cosmetic', 'manicure', 'fashion'] },
  { id: 'hat', emoji: '👒', name: 'Woman\'s Hat', category: 'shopping', keywords: ['accessory', 'fashion', 'headwear'] },
  { id: 'cap', emoji: '🧢', name: 'Billed Cap', category: 'shopping', keywords: ['accessory', 'fashion', 'headwear', 'baseball'] },
  { id: 'graduation-cap', emoji: '🎓', name: 'Graduation Cap', category: 'shopping', keywords: ['education', 'graduate', 'school', 'achievement'] },
  { id: 'scissors', emoji: '✂️', name: 'Scissors', category: 'shopping', keywords: ['tool', 'cut', 'craft', 'haircut'] },
  { id: 'yarn', emoji: '🧶', name: 'Yarn', category: 'shopping', keywords: ['craft', 'knitting', 'hobby', 'textile'] },
  { id: 'thread', emoji: '🧵', name: 'Thread', category: 'shopping', keywords: ['craft', 'sewing', 'hobby', 'textile'] },

  // ========== ACTIVITIES & ENTERTAINMENT ==========
  { id: 'movie-camera', emoji: '🎬', name: 'Clapper Board', category: 'activities', keywords: ['movie', 'film', 'cinema', 'entertainment'] },
  { id: 'theater', emoji: '🎭', name: 'Performing Arts', category: 'activities', keywords: ['theater', 'drama', 'entertainment', 'masks'] },
  { id: 'art', emoji: '🎨', name: 'Artist Palette', category: 'activities', keywords: ['art', 'painting', 'creative', 'hobby'] },
  { id: 'microphone', emoji: '🎤', name: 'Microphone', category: 'activities', keywords: ['music', 'singing', 'karaoke', 'entertainment'] },
  { id: 'headphones', emoji: '🎧', name: 'Headphone', category: 'activities', keywords: ['music', 'audio', 'listening', 'entertainment'] },
  { id: 'musical-notes', emoji: '🎵', name: 'Musical Note', category: 'activities', keywords: ['music', 'song', 'audio', 'sound'] },
  { id: 'guitar', emoji: '🎸', name: 'Guitar', category: 'activities', keywords: ['music', 'instrument', 'rock', 'entertainment'] },
  { id: 'piano', emoji: '🎹', name: 'Musical Keyboard', category: 'activities', keywords: ['music', 'instrument', 'piano', 'entertainment'] },
  { id: 'violin', emoji: '🎻', name: 'Violin', category: 'activities', keywords: ['music', 'instrument', 'classical', 'entertainment'] },
  { id: 'drum', emoji: '🥁', name: 'Drum', category: 'activities', keywords: ['music', 'instrument', 'percussion', 'entertainment'] },
  { id: 'video-game', emoji: '🎮', name: 'Video Game', category: 'activities', keywords: ['gaming', 'controller', 'entertainment', 'play'] },
  { id: 'joystick', emoji: '🕹️', name: 'Joystick', category: 'activities', keywords: ['gaming', 'arcade', 'entertainment', 'play'] },
  { id: 'slot-machine', emoji: '🎰', name: 'Slot Machine', category: 'activities', keywords: ['gambling', 'casino', 'entertainment', 'luck'] },
  { id: 'dice', emoji: '🎲', name: 'Game Die', category: 'activities', keywords: ['game', 'dice', 'board game', 'luck'] },
  { id: 'puzzle', emoji: '🧩', name: 'Puzzle Piece', category: 'activities', keywords: ['game', 'puzzle', 'hobby', 'solve'] },
  { id: 'chess', emoji: '♟️', name: 'Chess Pawn', category: 'activities', keywords: ['game', 'chess', 'strategy', 'board'] },
  { id: 'bowling', emoji: '🎳', name: 'Bowling', category: 'activities', keywords: ['sport', 'game', 'entertainment', 'pins'] },
  { id: 'target', emoji: '🎯', name: 'Direct Hit', category: 'activities', keywords: ['goal', 'target', 'aim', 'bullseye', 'darts'] },
  { id: 'soccer', emoji: '⚽', name: 'Soccer Ball', category: 'activities', keywords: ['sport', 'football', 'game', 'ball'] },
  { id: 'basketball', emoji: '🏀', name: 'Basketball', category: 'activities', keywords: ['sport', 'game', 'ball', 'hoop'] },
  { id: 'football', emoji: '🏈', name: 'American Football', category: 'activities', keywords: ['sport', 'game', 'ball', 'nfl'] },
  { id: 'baseball', emoji: '⚾', name: 'Baseball', category: 'activities', keywords: ['sport', 'game', 'ball', 'mlb'] },
  { id: 'tennis', emoji: '🎾', name: 'Tennis', category: 'activities', keywords: ['sport', 'game', 'ball', 'racket'] },
  { id: 'volleyball', emoji: '🏐', name: 'Volleyball', category: 'activities', keywords: ['sport', 'game', 'ball', 'beach'] },
  { id: 'rugby', emoji: '🏉', name: 'Rugby Football', category: 'activities', keywords: ['sport', 'game', 'ball'] },
  { id: 'golf', emoji: '⛳', name: 'Flag in Hole', category: 'activities', keywords: ['sport', 'golf', 'game', 'club'] },
  { id: 'ice-skate', emoji: '⛸️', name: 'Ice Skate', category: 'activities', keywords: ['sport', 'skating', 'winter', 'ice'] },
  { id: 'ski', emoji: '🎿', name: 'Skis', category: 'activities', keywords: ['sport', 'skiing', 'winter', 'snow'] },
  { id: 'fishing', emoji: '🎣', name: 'Fishing Pole', category: 'activities', keywords: ['hobby', 'fish', 'outdoor', 'sport'] },
  { id: 'camping', emoji: '🏕️', name: 'Camping', category: 'activities', keywords: ['outdoor', 'tent', 'nature', 'vacation'] },
  { id: 'ticket', emoji: '🎫', name: 'Ticket', category: 'activities', keywords: ['event', 'admission', 'entertainment', 'concert'] },
  { id: 'trophy', emoji: '🏆', name: 'Trophy', category: 'activities', keywords: ['award', 'winner', 'prize', 'achievement'] },
  { id: 'medal', emoji: '🏅', name: 'Sports Medal', category: 'activities', keywords: ['award', 'winner', 'prize', 'achievement'] },
  { id: 'book', emoji: '📚', name: 'Books', category: 'activities', keywords: ['reading', 'education', 'library', 'study'] },
  { id: 'notebook', emoji: '📓', name: 'Notebook', category: 'activities', keywords: ['writing', 'notes', 'journal', 'study'] },

  // ========== WORK & OFFICE ==========
  { id: 'briefcase-work', emoji: '💼', name: 'Briefcase', category: 'work', keywords: ['work', 'business', 'office', 'job', 'career'] },
  { id: 'file-folder', emoji: '📁', name: 'File Folder', category: 'work', keywords: ['office', 'documents', 'organize', 'files'] },
  { id: 'open-folder', emoji: '📂', name: 'Open File Folder', category: 'work', keywords: ['office', 'documents', 'organize', 'files'] },
  { id: 'card-index', emoji: '🗂️', name: 'Card Index Dividers', category: 'work', keywords: ['office', 'organize', 'files', 'tabs'] },
  { id: 'clipboard', emoji: '📋', name: 'Clipboard', category: 'work', keywords: ['office', 'notes', 'checklist', 'tasks'] },
  { id: 'pushpin', emoji: '📌', name: 'Pushpin', category: 'work', keywords: ['office', 'pin', 'note', 'important'] },
  { id: 'paperclip', emoji: '📎', name: 'Paperclip', category: 'work', keywords: ['office', 'attach', 'documents', 'clip'] },
  { id: 'ruler', emoji: '📏', name: 'Straight Ruler', category: 'work', keywords: ['office', 'measure', 'tool', 'school'] },
  { id: 'triangular-ruler', emoji: '📐', name: 'Triangular Ruler', category: 'work', keywords: ['office', 'measure', 'tool', 'geometry'] },
  { id: 'scissors-work', emoji: '✂️', name: 'Scissors', category: 'work', keywords: ['office', 'cut', 'tool', 'craft'] },
  { id: 'file-cabinet', emoji: '🗄️', name: 'File Cabinet', category: 'work', keywords: ['office', 'storage', 'files', 'organize'] },
  { id: 'wastebasket', emoji: '🗑️', name: 'Wastebasket', category: 'work', keywords: ['office', 'trash', 'delete', 'garbage'] },
  { id: 'calendar', emoji: '📅', name: 'Calendar', category: 'work', keywords: ['schedule', 'date', 'planning', 'appointment'] },
  { id: 'spiral-calendar', emoji: '🗓️', name: 'Spiral Calendar', category: 'work', keywords: ['schedule', 'date', 'planning', 'month'] },
  { id: 'card-file', emoji: '📇', name: 'Card Index', category: 'work', keywords: ['office', 'contacts', 'organize', 'rolodex'] },
  { id: 'chart', emoji: '📊', name: 'Bar Chart', category: 'work', keywords: ['data', 'statistics', 'graph', 'report'] },
  { id: 'memo', emoji: '📝', name: 'Memo', category: 'work', keywords: ['note', 'writing', 'document', 'reminder'] },
  { id: 'pen', emoji: '🖊️', name: 'Pen', category: 'work', keywords: ['writing', 'office', 'sign', 'document'] },
  { id: 'pencil', emoji: '✏️', name: 'Pencil', category: 'work', keywords: ['writing', 'office', 'draw', 'school'] },
  { id: 'envelope', emoji: '✉️', name: 'Envelope', category: 'work', keywords: ['mail', 'email', 'letter', 'message'] },
  { id: 'inbox', emoji: '📥', name: 'Inbox Tray', category: 'work', keywords: ['mail', 'email', 'receive', 'messages'] },
  { id: 'outbox', emoji: '📤', name: 'Outbox Tray', category: 'work', keywords: ['mail', 'email', 'send', 'messages'] },
  { id: 'mailbox', emoji: '📬', name: 'Open Mailbox with Raised Flag', category: 'work', keywords: ['mail', 'postal', 'letter', 'delivery'] },
  { id: 'package', emoji: '📦', name: 'Package', category: 'work', keywords: ['box', 'delivery', 'shipping', 'parcel'] },
  { id: 'alarm-clock', emoji: '⏰', name: 'Alarm Clock', category: 'work', keywords: ['time', 'wake', 'schedule', 'morning'] },
  { id: 'hourglass', emoji: '⏳', name: 'Hourglass', category: 'work', keywords: ['time', 'waiting', 'timer', 'sand'] },
  { id: 'stopwatch', emoji: '⏱️', name: 'Stopwatch', category: 'work', keywords: ['time', 'timer', 'speed', 'measure'] },

  // ========== TECH & DEVICES ==========
  { id: 'mobile-phone', emoji: '📱', name: 'Mobile Phone', category: 'tech', keywords: ['phone', 'smartphone', 'cell', 'device', 'app'] },
  { id: 'telephone', emoji: '📞', name: 'Telephone Receiver', category: 'tech', keywords: ['phone', 'call', 'communication'] },
  { id: 'laptop', emoji: '💻', name: 'Laptop', category: 'tech', keywords: ['computer', 'work', 'device', 'macbook'] },
  { id: 'desktop', emoji: '🖥️', name: 'Desktop Computer', category: 'tech', keywords: ['computer', 'pc', 'device', 'monitor'] },
  { id: 'keyboard', emoji: '⌨️', name: 'Keyboard', category: 'tech', keywords: ['computer', 'typing', 'device', 'input'] },
  { id: 'mouse', emoji: '🖱️', name: 'Computer Mouse', category: 'tech', keywords: ['computer', 'device', 'click', 'input'] },
  { id: 'printer', emoji: '🖨️', name: 'Printer', category: 'tech', keywords: ['computer', 'device', 'print', 'document'] },
  { id: 'television', emoji: '📺', name: 'Television', category: 'tech', keywords: ['tv', 'screen', 'entertainment', 'device'] },
  { id: 'camera', emoji: '📷', name: 'Camera', category: 'tech', keywords: ['photo', 'picture', 'device', 'photography'] },
  { id: 'video-camera', emoji: '📹', name: 'Video Camera', category: 'tech', keywords: ['video', 'film', 'device', 'recording'] },
  { id: 'watch', emoji: '⌚', name: 'Watch', category: 'tech', keywords: ['time', 'wearable', 'device', 'smartwatch'] },
  { id: 'battery', emoji: '🔋', name: 'Battery', category: 'tech', keywords: ['power', 'energy', 'charge', 'device'] },
  { id: 'satellite', emoji: '📡', name: 'Satellite Antenna', category: 'tech', keywords: ['communication', 'signal', 'dish', 'internet'] },
  { id: 'radio', emoji: '📻', name: 'Radio', category: 'tech', keywords: ['music', 'audio', 'entertainment', 'broadcast'] },
  { id: 'disk', emoji: '💾', name: 'Floppy Disk', category: 'tech', keywords: ['save', 'storage', 'data', 'computer'] },
  { id: 'cd', emoji: '💿', name: 'Optical Disk', category: 'tech', keywords: ['music', 'storage', 'data', 'disc'] },
  { id: 'dvd', emoji: '📀', name: 'DVD', category: 'tech', keywords: ['movie', 'storage', 'data', 'disc'] },
  { id: 'flashlight', emoji: '🔦', name: 'Flashlight', category: 'tech', keywords: ['light', 'torch', 'device', 'emergency'] },
  { id: 'magnifying-glass', emoji: '🔍', name: 'Magnifying Glass', category: 'tech', keywords: ['search', 'find', 'zoom', 'investigate'] },
  { id: 'robot', emoji: '🤖', name: 'Robot', category: 'tech', keywords: ['ai', 'automation', 'technology', 'machine'] },

  // ========== PEOPLE ==========
  { id: 'baby', emoji: '👶', name: 'Baby', category: 'people', keywords: ['child', 'infant', 'kid', 'family', 'newborn'] },
  { id: 'child', emoji: '🧒', name: 'Child', category: 'people', keywords: ['kid', 'young', 'family', 'person'] },
  { id: 'boy', emoji: '👦', name: 'Boy', category: 'people', keywords: ['child', 'kid', 'male', 'young'] },
  { id: 'girl', emoji: '👧', name: 'Girl', category: 'people', keywords: ['child', 'kid', 'female', 'young'] },
  { id: 'man', emoji: '👨', name: 'Man', category: 'people', keywords: ['adult', 'male', 'person', 'guy'] },
  { id: 'woman', emoji: '👩', name: 'Woman', category: 'people', keywords: ['adult', 'female', 'person', 'lady'] },
  { id: 'older-man', emoji: '👴', name: 'Old Man', category: 'people', keywords: ['elderly', 'senior', 'grandpa', 'grandfather'] },
  { id: 'older-woman', emoji: '👵', name: 'Old Woman', category: 'people', keywords: ['elderly', 'senior', 'grandma', 'grandmother'] },
  { id: 'family', emoji: '👪', name: 'Family', category: 'people', keywords: ['parents', 'children', 'home', 'household'] },
  { id: 'couple', emoji: '👫', name: 'Man and Woman Holding Hands', category: 'people', keywords: ['relationship', 'couple', 'love', 'partner'] },
  { id: 'person', emoji: '🧑', name: 'Person', category: 'people', keywords: ['adult', 'neutral', 'individual', 'human'] },
  { id: 'bust', emoji: '👤', name: 'Bust in Silhouette', category: 'people', keywords: ['person', 'user', 'profile', 'account'] },
  { id: 'busts', emoji: '👥', name: 'Busts in Silhouette', category: 'people', keywords: ['people', 'users', 'group', 'team'] },
  { id: 'waving', emoji: '👋', name: 'Waving Hand', category: 'people', keywords: ['hello', 'goodbye', 'wave', 'greeting'] },
  { id: 'thumbs-up', emoji: '👍', name: 'Thumbs Up', category: 'people', keywords: ['good', 'approve', 'like', 'yes'] },
  { id: 'thumbs-down', emoji: '👎', name: 'Thumbs Down', category: 'people', keywords: ['bad', 'disapprove', 'dislike', 'no'] },
  { id: 'clapping', emoji: '👏', name: 'Clapping Hands', category: 'people', keywords: ['applause', 'congratulations', 'bravo'] },
  { id: 'handshake', emoji: '🤝', name: 'Handshake', category: 'people', keywords: ['agreement', 'deal', 'meeting', 'partnership'] },
  { id: 'praying', emoji: '🙏', name: 'Folded Hands', category: 'people', keywords: ['prayer', 'thanks', 'please', 'hope'] },
  { id: 'muscle', emoji: '💪', name: 'Flexed Biceps', category: 'people', keywords: ['strong', 'power', 'gym', 'strength'] },

  // ========== ANIMALS ==========
  { id: 'dog', emoji: '🐕', name: 'Dog', category: 'animals', keywords: ['pet', 'animal', 'puppy', 'canine'] },
  { id: 'dog-face', emoji: '🐶', name: 'Dog Face', category: 'animals', keywords: ['pet', 'animal', 'puppy', 'cute'] },
  { id: 'cat', emoji: '🐈', name: 'Cat', category: 'animals', keywords: ['pet', 'animal', 'kitten', 'feline'] },
  { id: 'cat-face', emoji: '🐱', name: 'Cat Face', category: 'animals', keywords: ['pet', 'animal', 'kitten', 'cute'] },
  { id: 'rabbit', emoji: '🐇', name: 'Rabbit', category: 'animals', keywords: ['pet', 'animal', 'bunny', 'easter'] },
  { id: 'hamster', emoji: '🐹', name: 'Hamster', category: 'animals', keywords: ['pet', 'animal', 'rodent', 'cute'] },
  { id: 'mouse-animal', emoji: '🐭', name: 'Mouse Face', category: 'animals', keywords: ['animal', 'rodent', 'small'] },
  { id: 'fish', emoji: '🐠', name: 'Tropical Fish', category: 'animals', keywords: ['pet', 'animal', 'aquarium', 'sea'] },
  { id: 'bird', emoji: '🐦', name: 'Bird', category: 'animals', keywords: ['pet', 'animal', 'fly', 'feather'] },
  { id: 'parrot', emoji: '🦜', name: 'Parrot', category: 'animals', keywords: ['pet', 'bird', 'tropical', 'colorful'] },
  { id: 'turtle', emoji: '🐢', name: 'Turtle', category: 'animals', keywords: ['pet', 'animal', 'reptile', 'slow'] },
  { id: 'snake', emoji: '🐍', name: 'Snake', category: 'animals', keywords: ['animal', 'reptile', 'slither'] },
  { id: 'lizard', emoji: '🦎', name: 'Lizard', category: 'animals', keywords: ['pet', 'animal', 'reptile', 'gecko'] },
  { id: 'paw-prints', emoji: '🐾', name: 'Paw Prints', category: 'animals', keywords: ['pet', 'animal', 'tracks', 'footprint'] },
  { id: 'bone', emoji: '🦴', name: 'Bone', category: 'animals', keywords: ['pet', 'dog', 'treat', 'skeleton'] },
  { id: 'horse', emoji: '🐎', name: 'Horse', category: 'animals', keywords: ['animal', 'equine', 'racing', 'ride'] },
  { id: 'cow', emoji: '🐄', name: 'Cow', category: 'animals', keywords: ['animal', 'farm', 'milk', 'beef'] },
  { id: 'pig', emoji: '🐷', name: 'Pig Face', category: 'animals', keywords: ['animal', 'farm', 'pork', 'oink'] },
  { id: 'sheep', emoji: '🐑', name: 'Ewe', category: 'animals', keywords: ['animal', 'farm', 'wool', 'lamb'] },
  { id: 'chicken', emoji: '🐔', name: 'Chicken', category: 'animals', keywords: ['animal', 'farm', 'poultry', 'hen'] },
  { id: 'duck', emoji: '🦆', name: 'Duck', category: 'animals', keywords: ['animal', 'bird', 'water', 'quack'] },
  { id: 'bee', emoji: '🐝', name: 'Honeybee', category: 'animals', keywords: ['insect', 'honey', 'buzz', 'sting'] },
  { id: 'butterfly', emoji: '🦋', name: 'Butterfly', category: 'animals', keywords: ['insect', 'beautiful', 'nature', 'metamorphosis'] },
  { id: 'ladybug', emoji: '🐞', name: 'Lady Beetle', category: 'animals', keywords: ['insect', 'bug', 'luck', 'nature'] },

  // ========== NATURE ==========
  { id: 'sun', emoji: '☀️', name: 'Sun', category: 'nature', keywords: ['weather', 'sunny', 'hot', 'bright', 'summer'] },
  { id: 'moon', emoji: '🌙', name: 'Crescent Moon', category: 'nature', keywords: ['night', 'sky', 'sleep', 'dark'] },
  { id: 'star', emoji: '⭐', name: 'Star', category: 'nature', keywords: ['favorite', 'night', 'sky', 'rating'] },
  { id: 'sparkles', emoji: '✨', name: 'Sparkles', category: 'nature', keywords: ['shine', 'magic', 'clean', 'new'] },
  { id: 'cloud', emoji: '☁️', name: 'Cloud', category: 'nature', keywords: ['weather', 'sky', 'cloudy', 'overcast'] },
  { id: 'rain', emoji: '🌧️', name: 'Cloud with Rain', category: 'nature', keywords: ['weather', 'rainy', 'water', 'wet'] },
  { id: 'snow', emoji: '❄️', name: 'Snowflake', category: 'nature', keywords: ['weather', 'winter', 'cold', 'frozen'] },
  { id: 'rainbow', emoji: '🌈', name: 'Rainbow', category: 'nature', keywords: ['weather', 'colorful', 'nature', 'pride'] },
  { id: 'lightning', emoji: '⚡', name: 'High Voltage', category: 'nature', keywords: ['weather', 'electric', 'power', 'storm'] },
  { id: 'fire', emoji: '🔥', name: 'Fire', category: 'nature', keywords: ['hot', 'flame', 'burn', 'popular'] },
  { id: 'water-wave', emoji: '🌊', name: 'Water Wave', category: 'nature', keywords: ['ocean', 'sea', 'beach', 'surf'] },
  { id: 'tree', emoji: '🌳', name: 'Deciduous Tree', category: 'nature', keywords: ['nature', 'forest', 'plant', 'green'] },
  { id: 'palm-tree', emoji: '🌴', name: 'Palm Tree', category: 'nature', keywords: ['tropical', 'beach', 'vacation', 'summer'] },
  { id: 'evergreen', emoji: '🌲', name: 'Evergreen Tree', category: 'nature', keywords: ['nature', 'forest', 'pine', 'christmas'] },
  { id: 'cactus', emoji: '🌵', name: 'Cactus', category: 'nature', keywords: ['plant', 'desert', 'nature', 'succulent'] },
  { id: 'flower', emoji: '🌸', name: 'Cherry Blossom', category: 'nature', keywords: ['flower', 'spring', 'nature', 'pink'] },
  { id: 'sunflower', emoji: '🌻', name: 'Sunflower', category: 'nature', keywords: ['flower', 'summer', 'nature', 'yellow'] },
  { id: 'rose', emoji: '🌹', name: 'Rose', category: 'nature', keywords: ['flower', 'love', 'romance', 'red'] },
  { id: 'tulip', emoji: '🌷', name: 'Tulip', category: 'nature', keywords: ['flower', 'spring', 'nature', 'pink'] },
  { id: 'hibiscus', emoji: '🌺', name: 'Hibiscus', category: 'nature', keywords: ['flower', 'tropical', 'nature', 'hawaii'] },
  { id: 'seedling', emoji: '🌱', name: 'Seedling', category: 'nature', keywords: ['plant', 'growth', 'nature', 'new'] },
  { id: 'leaf', emoji: '🍃', name: 'Leaf Fluttering in Wind', category: 'nature', keywords: ['nature', 'green', 'plant', 'wind'] },
  { id: 'maple-leaf', emoji: '🍁', name: 'Maple Leaf', category: 'nature', keywords: ['nature', 'fall', 'autumn', 'canada'] },
  { id: 'fallen-leaf', emoji: '🍂', name: 'Fallen Leaf', category: 'nature', keywords: ['nature', 'fall', 'autumn', 'brown'] },
  { id: 'mountain', emoji: '⛰️', name: 'Mountain', category: 'nature', keywords: ['nature', 'hiking', 'outdoor', 'peak'] },
  { id: 'volcano', emoji: '🌋', name: 'Volcano', category: 'nature', keywords: ['nature', 'lava', 'eruption', 'mountain'] },
  { id: 'beach', emoji: '🏖️', name: 'Beach with Umbrella', category: 'nature', keywords: ['vacation', 'summer', 'sand', 'ocean'] },
  { id: 'desert', emoji: '🏜️', name: 'Desert', category: 'nature', keywords: ['nature', 'sand', 'hot', 'dry'] },
  { id: 'island', emoji: '🏝️', name: 'Desert Island', category: 'nature', keywords: ['tropical', 'vacation', 'beach', 'palm'] },
  { id: 'globe', emoji: '🌍', name: 'Globe Showing Europe-Africa', category: 'nature', keywords: ['earth', 'world', 'planet', 'global'] },
  { id: 'earth', emoji: '🌎', name: 'Globe Showing Americas', category: 'nature', keywords: ['earth', 'world', 'planet', 'global'] },
  { id: 'recycle', emoji: '♻️', name: 'Recycling Symbol', category: 'nature', keywords: ['environment', 'green', 'eco', 'sustainable'] },

  // ========== OBJECTS ==========
  { id: 'gift', emoji: '🎁', name: 'Wrapped Gift', category: 'objects', keywords: ['present', 'birthday', 'christmas', 'celebration'] },
  { id: 'balloon', emoji: '🎈', name: 'Balloon', category: 'objects', keywords: ['party', 'celebration', 'birthday', 'fun'] },
  { id: 'confetti', emoji: '🎉', name: 'Party Popper', category: 'objects', keywords: ['celebration', 'party', 'congratulations', 'hooray'] },
  { id: 'sparkler', emoji: '🎇', name: 'Sparkler', category: 'objects', keywords: ['celebration', 'fireworks', 'new year'] },
  { id: 'fireworks', emoji: '🎆', name: 'Fireworks', category: 'objects', keywords: ['celebration', 'new year', 'festival'] },
  { id: 'bell', emoji: '🔔', name: 'Bell', category: 'objects', keywords: ['notification', 'alert', 'ring', 'alarm'] },
  { id: 'christmas-tree', emoji: '🎄', name: 'Christmas Tree', category: 'objects', keywords: ['christmas', 'holiday', 'decoration', 'winter'] },
  { id: 'jack-o-lantern', emoji: '🎃', name: 'Jack-O-Lantern', category: 'objects', keywords: ['halloween', 'pumpkin', 'spooky', 'october'] },
  { id: 'candle', emoji: '🕯️', name: 'Candle', category: 'objects', keywords: ['light', 'romantic', 'decoration', 'flame'] },
  { id: 'umbrella', emoji: '☂️', name: 'Umbrella', category: 'objects', keywords: ['rain', 'weather', 'protection', 'wet'] },
  { id: 'label', emoji: '🏷️', name: 'Label', category: 'objects', keywords: ['tag', 'price', 'sale', 'name'] },
  { id: 'bookmark', emoji: '🔖', name: 'Bookmark', category: 'objects', keywords: ['reading', 'book', 'save', 'mark'] },
  { id: 'scroll', emoji: '📜', name: 'Scroll', category: 'objects', keywords: ['document', 'paper', 'ancient', 'writing'] },
  { id: 'newspaper', emoji: '📰', name: 'Newspaper', category: 'objects', keywords: ['news', 'reading', 'media', 'press'] },
  { id: 'money-envelope', emoji: '💴', name: 'Yen Banknote', category: 'objects', keywords: ['money', 'gift', 'lucky', 'cash'] },
  { id: 'love-letter', emoji: '💌', name: 'Love Letter', category: 'objects', keywords: ['mail', 'romance', 'heart', 'message'] },
  { id: 'speech-balloon', emoji: '💬', name: 'Speech Balloon', category: 'objects', keywords: ['chat', 'talk', 'message', 'communication'] },
  { id: 'thought-balloon', emoji: '💭', name: 'Thought Balloon', category: 'objects', keywords: ['think', 'idea', 'dream', 'imagination'] },
  { id: 'zzz', emoji: '💤', name: 'Zzz', category: 'objects', keywords: ['sleep', 'tired', 'rest', 'nap'] },
  { id: 'bomb', emoji: '💣', name: 'Bomb', category: 'objects', keywords: ['danger', 'explosive', 'warning'] },
  { id: 'hole', emoji: '🕳️', name: 'Hole', category: 'objects', keywords: ['black', 'empty', 'void', 'pit'] },
  { id: 'shopping-bag', emoji: '🛍️', name: 'Shopping Bags', category: 'objects', keywords: ['retail', 'buy', 'mall', 'purchase'] },
  { id: 'toilet', emoji: '🚽', name: 'Toilet', category: 'objects', keywords: ['bathroom', 'restroom', 'wc', 'lavatory'] },

  // ========== SYMBOLS ==========
  { id: 'heart-red', emoji: '❤️', name: 'Red Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'romance'] },
  { id: 'heart-orange', emoji: '🧡', name: 'Orange Heart', category: 'symbols', keywords: ['love', 'like', 'favorite'] },
  { id: 'heart-yellow', emoji: '💛', name: 'Yellow Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'friendship'] },
  { id: 'heart-green', emoji: '💚', name: 'Green Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'nature'] },
  { id: 'heart-blue', emoji: '💙', name: 'Blue Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'trust'] },
  { id: 'heart-purple', emoji: '💜', name: 'Purple Heart', category: 'symbols', keywords: ['love', 'like', 'favorite'] },
  { id: 'heart-black', emoji: '🖤', name: 'Black Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'dark'] },
  { id: 'heart-white', emoji: '🤍', name: 'White Heart', category: 'symbols', keywords: ['love', 'like', 'favorite', 'pure'] },
  { id: 'heart-brown', emoji: '🤎', name: 'Brown Heart', category: 'symbols', keywords: ['love', 'like', 'favorite'] },
  { id: 'broken-heart', emoji: '💔', name: 'Broken Heart', category: 'symbols', keywords: ['sad', 'breakup', 'heartbroken'] },
  { id: 'sparkling-heart', emoji: '💖', name: 'Sparkling Heart', category: 'symbols', keywords: ['love', 'like', 'excited', 'shiny'] },
  { id: 'growing-heart', emoji: '💗', name: 'Growing Heart', category: 'symbols', keywords: ['love', 'like', 'nervous', 'excited'] },
  { id: 'heart-exclamation', emoji: '❣️', name: 'Heart Exclamation', category: 'symbols', keywords: ['love', 'like', 'emphasis'] },
  { id: 'two-hearts', emoji: '💕', name: 'Two Hearts', category: 'symbols', keywords: ['love', 'like', 'affection'] },
  { id: 'check-mark', emoji: '✅', name: 'Check Mark Button', category: 'symbols', keywords: ['done', 'complete', 'yes', 'approved'] },
  { id: 'cross-mark', emoji: '❌', name: 'Cross Mark', category: 'symbols', keywords: ['no', 'wrong', 'error', 'delete'] },
  { id: 'warning', emoji: '⚠️', name: 'Warning', category: 'symbols', keywords: ['alert', 'caution', 'danger', 'attention'] },
  { id: 'no-entry', emoji: '⛔', name: 'No Entry', category: 'symbols', keywords: ['stop', 'forbidden', 'prohibited'] },
  { id: 'prohibited', emoji: '🚫', name: 'Prohibited', category: 'symbols', keywords: ['no', 'forbidden', 'stop', 'banned'] },
  { id: 'question', emoji: '❓', name: 'Question Mark', category: 'symbols', keywords: ['help', 'what', 'confused', 'ask'] },
  { id: 'exclamation', emoji: '❗', name: 'Exclamation Mark', category: 'symbols', keywords: ['important', 'attention', 'alert'] },
  { id: 'plus', emoji: '➕', name: 'Plus', category: 'symbols', keywords: ['add', 'math', 'more', 'positive'] },
  { id: 'minus', emoji: '➖', name: 'Minus', category: 'symbols', keywords: ['subtract', 'math', 'less', 'negative'] },
  { id: 'multiply', emoji: '✖️', name: 'Multiply', category: 'symbols', keywords: ['math', 'times', 'calculation'] },
  { id: 'divide', emoji: '➗', name: 'Divide', category: 'symbols', keywords: ['math', 'division', 'calculation'] },
  { id: 'infinity', emoji: '♾️', name: 'Infinity', category: 'symbols', keywords: ['forever', 'endless', 'math', 'unlimited'] },
  { id: 'hundred', emoji: '💯', name: 'Hundred Points', category: 'symbols', keywords: ['perfect', 'score', 'full', '100'] },
  { id: 'arrow-right', emoji: '➡️', name: 'Right Arrow', category: 'symbols', keywords: ['direction', 'next', 'forward'] },
  { id: 'arrow-left', emoji: '⬅️', name: 'Left Arrow', category: 'symbols', keywords: ['direction', 'back', 'previous'] },
  { id: 'arrow-up', emoji: '⬆️', name: 'Up Arrow', category: 'symbols', keywords: ['direction', 'up', 'increase'] },
  { id: 'arrow-down', emoji: '⬇️', name: 'Down Arrow', category: 'symbols', keywords: ['direction', 'down', 'decrease'] },
  { id: 'refresh', emoji: '🔄', name: 'Counterclockwise Arrows Button', category: 'symbols', keywords: ['refresh', 'reload', 'sync', 'repeat'] },
  { id: 'play', emoji: '▶️', name: 'Play Button', category: 'symbols', keywords: ['start', 'media', 'video', 'music'] },
  { id: 'pause', emoji: '⏸️', name: 'Pause Button', category: 'symbols', keywords: ['stop', 'media', 'video', 'music'] },
  { id: 'stop', emoji: '⏹️', name: 'Stop Button', category: 'symbols', keywords: ['end', 'media', 'video', 'music'] },
  { id: 'new', emoji: '🆕', name: 'New Button', category: 'symbols', keywords: ['fresh', 'recent', 'latest'] },
  { id: 'free', emoji: '🆓', name: 'Free Button', category: 'symbols', keywords: ['no cost', 'gratis', 'complimentary'] },
  { id: 'ok', emoji: '🆗', name: 'OK Button', category: 'symbols', keywords: ['okay', 'good', 'approve', 'yes'] },
  { id: 'sos', emoji: '🆘', name: 'SOS Button', category: 'symbols', keywords: ['help', 'emergency', 'rescue'] },
  { id: 'information', emoji: 'ℹ️', name: 'Information', category: 'symbols', keywords: ['info', 'help', 'details'] },
  { id: 'atm-sign', emoji: '🏧', name: 'ATM Sign', category: 'symbols', keywords: ['bank', 'cash', 'money', 'withdraw'] },
  { id: 'parking-sign', emoji: '🅿️', name: 'P Button', category: 'symbols', keywords: ['parking', 'car', 'lot'] },
  { id: 'restroom', emoji: '🚻', name: 'Restroom', category: 'symbols', keywords: ['toilet', 'bathroom', 'wc'] },
  { id: 'mens', emoji: '🚹', name: 'Men\'s Room', category: 'symbols', keywords: ['toilet', 'bathroom', 'male'] },
  { id: 'womens', emoji: '🚺', name: 'Women\'s Room', category: 'symbols', keywords: ['toilet', 'bathroom', 'female'] },
  { id: 'baby-symbol', emoji: '🚼', name: 'Baby Symbol', category: 'symbols', keywords: ['child', 'infant', 'changing room'] },
  { id: 'wheelchair-sign', emoji: '♿', name: 'Wheelchair Symbol', category: 'symbols', keywords: ['accessibility', 'disabled', 'handicap'] },
  { id: 'circle-red', emoji: '🔴', name: 'Red Circle', category: 'symbols', keywords: ['red', 'circle', 'dot', 'stop'] },
  { id: 'circle-orange', emoji: '🟠', name: 'Orange Circle', category: 'symbols', keywords: ['orange', 'circle', 'dot'] },
  { id: 'circle-yellow', emoji: '🟡', name: 'Yellow Circle', category: 'symbols', keywords: ['yellow', 'circle', 'dot'] },
  { id: 'circle-green', emoji: '🟢', name: 'Green Circle', category: 'symbols', keywords: ['green', 'circle', 'dot', 'go'] },
  { id: 'circle-blue', emoji: '🔵', name: 'Blue Circle', category: 'symbols', keywords: ['blue', 'circle', 'dot'] },
  { id: 'circle-purple', emoji: '🟣', name: 'Purple Circle', category: 'symbols', keywords: ['purple', 'circle', 'dot'] },
  { id: 'circle-black', emoji: '⚫', name: 'Black Circle', category: 'symbols', keywords: ['black', 'circle', 'dot'] },
  { id: 'circle-white', emoji: '⚪', name: 'White Circle', category: 'symbols', keywords: ['white', 'circle', 'dot'] },
  { id: 'square-red', emoji: '🟥', name: 'Red Square', category: 'symbols', keywords: ['red', 'square', 'box'] },
  { id: 'square-blue', emoji: '🟦', name: 'Blue Square', category: 'symbols', keywords: ['blue', 'square', 'box'] },
  { id: 'square-green', emoji: '🟩', name: 'Green Square', category: 'symbols', keywords: ['green', 'square', 'box'] },
  { id: 'diamond-orange', emoji: '🔶', name: 'Large Orange Diamond', category: 'symbols', keywords: ['orange', 'diamond', 'shape'] },
  { id: 'diamond-blue', emoji: '🔷', name: 'Large Blue Diamond', category: 'symbols', keywords: ['blue', 'diamond', 'shape'] },

  // ========== FLAGS ==========
  { id: 'flag-checkered', emoji: '🏁', name: 'Chequered Flag', category: 'flags', keywords: ['racing', 'finish', 'complete', 'end'] },
  { id: 'flag-triangular', emoji: '🚩', name: 'Triangular Flag', category: 'flags', keywords: ['flag', 'report', 'warning'] },
  { id: 'flag-crossed', emoji: '🎌', name: 'Crossed Flags', category: 'flags', keywords: ['japan', 'celebration', 'festival'] },
  { id: 'flag-black', emoji: '🏴', name: 'Black Flag', category: 'flags', keywords: ['flag', 'pirate', 'dark'] },
  { id: 'flag-white', emoji: '🏳️', name: 'White Flag', category: 'flags', keywords: ['surrender', 'peace', 'truce'] },
  { id: 'flag-rainbow', emoji: '🏳️‍🌈', name: 'Rainbow Flag', category: 'flags', keywords: ['pride', 'lgbtq', 'rainbow', 'equality'] },
  { id: 'flag-pirate', emoji: '🏴‍☠️', name: 'Pirate Flag', category: 'flags', keywords: ['pirate', 'skull', 'jolly roger'] },
  { id: 'flag-nz', emoji: '🇳🇿', name: 'Flag: New Zealand', category: 'flags', keywords: ['nz', 'new zealand', 'kiwi', 'aotearoa'] },
  { id: 'flag-au', emoji: '🇦🇺', name: 'Flag: Australia', category: 'flags', keywords: ['australia', 'aussie', 'oz'] },
  { id: 'flag-gb', emoji: '🇬🇧', name: 'Flag: United Kingdom', category: 'flags', keywords: ['uk', 'britain', 'england', 'british'] },
  { id: 'flag-us', emoji: '🇺🇸', name: 'Flag: United States', category: 'flags', keywords: ['usa', 'america', 'american'] },
  { id: 'flag-ca', emoji: '🇨🇦', name: 'Flag: Canada', category: 'flags', keywords: ['canada', 'canadian', 'maple'] },
  { id: 'flag-jp', emoji: '🇯🇵', name: 'Flag: Japan', category: 'flags', keywords: ['japan', 'japanese', 'nihon'] },
  { id: 'flag-kr', emoji: '🇰🇷', name: 'Flag: South Korea', category: 'flags', keywords: ['korea', 'korean', 'south korea'] },
  { id: 'flag-cn', emoji: '🇨🇳', name: 'Flag: China', category: 'flags', keywords: ['china', 'chinese', 'prc'] },
  { id: 'flag-in', emoji: '🇮🇳', name: 'Flag: India', category: 'flags', keywords: ['india', 'indian', 'bharat'] },
  { id: 'flag-br', emoji: '🇧🇷', name: 'Flag: Brazil', category: 'flags', keywords: ['brazil', 'brazilian', 'brasil'] },
  { id: 'flag-fr', emoji: '🇫🇷', name: 'Flag: France', category: 'flags', keywords: ['france', 'french', 'paris'] },
  { id: 'flag-de', emoji: '🇩🇪', name: 'Flag: Germany', category: 'flags', keywords: ['germany', 'german', 'deutschland'] },
  { id: 'flag-it', emoji: '🇮🇹', name: 'Flag: Italy', category: 'flags', keywords: ['italy', 'italian', 'italia'] },
  { id: 'flag-es', emoji: '🇪🇸', name: 'Flag: Spain', category: 'flags', keywords: ['spain', 'spanish', 'espana'] },
  { id: 'flag-mx', emoji: '🇲🇽', name: 'Flag: Mexico', category: 'flags', keywords: ['mexico', 'mexican'] },
  { id: 'flag-za', emoji: '🇿🇦', name: 'Flag: South Africa', category: 'flags', keywords: ['south africa', 'african'] },
  { id: 'flag-ie', emoji: '🇮🇪', name: 'Flag: Ireland', category: 'flags', keywords: ['ireland', 'irish', 'eire'] },
  { id: 'flag-sg', emoji: '🇸🇬', name: 'Flag: Singapore', category: 'flags', keywords: ['singapore', 'singaporean'] },
  { id: 'flag-hk', emoji: '🇭🇰', name: 'Flag: Hong Kong', category: 'flags', keywords: ['hong kong', 'hk'] },
  { id: 'flag-tw', emoji: '🇹🇼', name: 'Flag: Taiwan', category: 'flags', keywords: ['taiwan', 'taiwanese'] },
  { id: 'flag-th', emoji: '🇹🇭', name: 'Flag: Thailand', category: 'flags', keywords: ['thailand', 'thai'] },
  { id: 'flag-vn', emoji: '🇻🇳', name: 'Flag: Vietnam', category: 'flags', keywords: ['vietnam', 'vietnamese'] },
  { id: 'flag-ph', emoji: '🇵🇭', name: 'Flag: Philippines', category: 'flags', keywords: ['philippines', 'filipino', 'pinoy'] },
  { id: 'flag-id', emoji: '🇮🇩', name: 'Flag: Indonesia', category: 'flags', keywords: ['indonesia', 'indonesian'] },
  { id: 'flag-my', emoji: '🇲🇾', name: 'Flag: Malaysia', category: 'flags', keywords: ['malaysia', 'malaysian'] },
  { id: 'flag-ae', emoji: '🇦🇪', name: 'Flag: United Arab Emirates', category: 'flags', keywords: ['uae', 'dubai', 'emirates'] },
  { id: 'flag-sa', emoji: '🇸🇦', name: 'Flag: Saudi Arabia', category: 'flags', keywords: ['saudi arabia', 'saudi', 'ksa'] },
  { id: 'flag-nl', emoji: '🇳🇱', name: 'Flag: Netherlands', category: 'flags', keywords: ['netherlands', 'dutch', 'holland'] },
  { id: 'flag-be', emoji: '🇧🇪', name: 'Flag: Belgium', category: 'flags', keywords: ['belgium', 'belgian'] },
  { id: 'flag-ch', emoji: '🇨🇭', name: 'Flag: Switzerland', category: 'flags', keywords: ['switzerland', 'swiss'] },
  { id: 'flag-at', emoji: '🇦🇹', name: 'Flag: Austria', category: 'flags', keywords: ['austria', 'austrian'] },
  { id: 'flag-se', emoji: '🇸🇪', name: 'Flag: Sweden', category: 'flags', keywords: ['sweden', 'swedish'] },
  { id: 'flag-no', emoji: '🇳🇴', name: 'Flag: Norway', category: 'flags', keywords: ['norway', 'norwegian'] },
  { id: 'flag-dk', emoji: '🇩🇰', name: 'Flag: Denmark', category: 'flags', keywords: ['denmark', 'danish'] },
  { id: 'flag-fi', emoji: '🇫🇮', name: 'Flag: Finland', category: 'flags', keywords: ['finland', 'finnish'] },
  { id: 'flag-pl', emoji: '🇵🇱', name: 'Flag: Poland', category: 'flags', keywords: ['poland', 'polish'] },
  { id: 'flag-ru', emoji: '🇷🇺', name: 'Flag: Russia', category: 'flags', keywords: ['russia', 'russian'] },
  { id: 'flag-ua', emoji: '🇺🇦', name: 'Flag: Ukraine', category: 'flags', keywords: ['ukraine', 'ukrainian'] },
  { id: 'flag-gr', emoji: '🇬🇷', name: 'Flag: Greece', category: 'flags', keywords: ['greece', 'greek'] },
  { id: 'flag-tr', emoji: '🇹🇷', name: 'Flag: Turkey', category: 'flags', keywords: ['turkey', 'turkish'] },
  { id: 'flag-il', emoji: '🇮🇱', name: 'Flag: Israel', category: 'flags', keywords: ['israel', 'israeli'] },
  { id: 'flag-eg', emoji: '🇪🇬', name: 'Flag: Egypt', category: 'flags', keywords: ['egypt', 'egyptian'] },
  { id: 'flag-ng', emoji: '🇳🇬', name: 'Flag: Nigeria', category: 'flags', keywords: ['nigeria', 'nigerian'] },
  { id: 'flag-ke', emoji: '🇰🇪', name: 'Flag: Kenya', category: 'flags', keywords: ['kenya', 'kenyan'] },
  { id: 'flag-ar', emoji: '🇦🇷', name: 'Flag: Argentina', category: 'flags', keywords: ['argentina', 'argentinian'] },
  { id: 'flag-cl', emoji: '🇨🇱', name: 'Flag: Chile', category: 'flags', keywords: ['chile', 'chilean'] },
  { id: 'flag-co', emoji: '🇨🇴', name: 'Flag: Colombia', category: 'flags', keywords: ['colombia', 'colombian'] },
  { id: 'flag-pe', emoji: '🇵🇪', name: 'Flag: Peru', category: 'flags', keywords: ['peru', 'peruvian'] },
];

// Helper function to get emojis by category
export function getEmojisByCategory(category: string): FluentEmoji[] {
  return FLUENT_EMOJIS.filter(e => e.category === category);
}

// Helper function to search emojis
export function searchEmojis(query: string): FluentEmoji[] {
  const lowerQuery = query.toLowerCase().trim();
  if (!lowerQuery) return [];

  return FLUENT_EMOJIS.filter(
    e =>
      e.name.toLowerCase().includes(lowerQuery) ||
      e.keywords.some(k => k.toLowerCase().includes(lowerQuery))
  );
}

// Get total emoji count
export const TOTAL_EMOJI_COUNT = FLUENT_EMOJIS.length;
