import type { PlannerEnvelope } from "@/app/(app)/envelope-planning/planner-client";

export const demoPlannerEnvelopes: PlannerEnvelope[] = [
  {
    id: "demo-rent",
    name: "Rent",
    category_id: null,
    category_name: "Housing",
    target_amount: 2200,
    annual_amount: 26400,
    pay_cycle_amount: 1100,
    opening_balance: 0,
    current_amount: 2200,
    due_date: "2025-08-01",
    next_payment_due: "2025-08-01",
    frequency: "monthly",
    notes: "Pay on the 1st",
  },
  {
    id: "demo-groceries",
    name: "Groceries",
    category_id: null,
    category_name: "Essentials",
    target_amount: 300,
    annual_amount: 15600,
    pay_cycle_amount: 150,
    opening_balance: 0,
    current_amount: 240,
    due_date: null,
    next_payment_due: null,
    frequency: "weekly",
    notes: "Countdown & New World",
  },
  {
    id: "demo-holiday",
    name: "Holiday fund",
    category_id: null,
    category_name: "Savings",
    target_amount: 5000,
    annual_amount: 5000,
    pay_cycle_amount: 200,
    opening_balance: 0,
    current_amount: 1250,
    due_date: "2025-12-10",
    next_payment_due: "2025-12-10",
    frequency: "annually",
    notes: "Trip to Rarotonga",
  },
];
